services:
  db:
    image: postgres:16
    container_name: portfolio_local_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: