name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'portfolio_BE/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'portfolio_BE/**'
      - '.github/workflows/backend.yml'

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    env: 
      DB_URL: ${{ secrets.DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USER }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}


    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: portfolio
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.DB_USER}} -d portfolio"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    defaults:
      run:
        working-directory: portfolio_BE

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install psql client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h 127.0.0.1 -p 5432 -U ${{ secrets.DB_USER }} -d portfolio && break
            echo "Postgres not ready yet... ($i)"; sleep 2
          done

      - name: Build
        run: ./gradlew --no-daemon clean assemble

      - name: Run tests (uses Postgres)
        run: ./gradlew --no-daemon test

      - name: Upload test report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-report
          path: portfolio_BE/build/reports/tests/test

      - name: Upload JAR (on success)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: portfolio_BE/build/libs/*.jar
